.gitignore, api/python/Makefile, api/python/pyproject.toml
- the lincense file needs to be included for legal reason.
- add license to python package
- add packaging recipes to make file and run them when installing.
- ran make install and check the build and egg-info has the expect license.
- ran make cleanup and check the license file was cleaned up.
=> feat: include license file with python package

api/python/src/cellxgene_ontology_guide/artifact_download.py, api/python/src/cellxgene_ontology_guide/entities.py, api/python/src/cellxgene_ontology_guide/ontology_parser.py, api/python/tests/test_artifact_download.py, api/python/tests/test_ontology_parser.py
- #22
- clean up / refactor OntologyParser class and load_artifact_by_schema function
- remove multi-ton implementation (deemed overengineering + potential for memory leaks upon further review)
- add function to OntologyParser to construct download links for ontologies from their source repo
- added enums to limit inputs only to construct URLs for known ontology/file variants/file types
- unit tests
- further changes around how we fetch + package the data the OntologyParser reads from will be addressed in separate PRs
=> feat: Support getting download link for ontology from source repo

api/python/MANIFEST.in, api/python/Makefile, api/python/pyproject.toml, api/python/src/cellxgene_ontology_guide/constants.py
- This is to make tracking the supported version easier per release of the cellxgene-ontology-guide python api
- packaging the ontology-assets with the python library under cellxgene-ontology-guide/data
- make install the API and verified the files exist
- make clean the API and verified the files were removed.
=> feat: add data to the python package 

api/python/src/cellxgene_ontology_guide/constants.py, api/python/src/cellxgene_ontology_guide/ontology_parser.py, api/python/tests/test_ontology_parser.py
- support "unknown" and "na" term_ids, which are non-ontology BUT are valid substitutes according to the CxG schema. Note that we may need to version this behavior, should it change in the future (i.e. acceptable non-ontology term added, removed)
- rename all bulk fetch methods --> "map_<subject>" 
- rename all single fetch methods --> "get_<subject>"
- added single fetch methods for high level terms, highest level terms, term descendants
- added bulk fetch method for ancestors_with_distances and term labels
- reordered ontology_parser to follow more logical method declarations (but this is causing the diff to look larger than it is, so I can revert if its confusing to review...)
=> chore: clean-up ontology_parser single fetch and bulk fetch methods + account for acceptable non-ontology terms

api/python/pyproject.toml, tools/ontology-builder/requirements.txt
- The API should have relax requirements to avoid being incompatible the downstream consumers
- We no long use pyyaml
- relax versioning
- remove unused PyYaml requirement
- unit tests
=> fix: update requirements

api/python/src/cellxgene_ontology_guide/ontology_parser.py, api/python/tests/test_ontology_parser.py
- helper function utilized in cellxgene-schema validator 
- add is_valid_term_id method, returns bool determining if a term_id is from a valid ontology and is defined in the given schema version's corresponding ontology. If deprecated but defined in the ontology, it IS a valid term.
=> feat: add is_valid_term_id method to OntologyParser

.github/workflows/release.yml, api/python/Makefile
- release to pypi form GHA
- modify release.yml to release to pypi
- use [trust release](https://docs.pypi.org/trusted-publishers/) instead of personal access token.
- added comments to api/python/makefile to suggested users only publish using the make if CICD is not working.
- Generated a release, and publish to test pypi.
=> chore: use trusted publisher to publish pypi package.

.github/workflows/push-tests.yml, .gitignore, Makefile, api/python/Makefile, api/python/pyproject.toml, tools/coverage.mk, tools/ontology-builder/Makefile, tools/ontology-builder/requirements-dev.txt
enable code coverage to help maintain a high coding standard
- enable code coverage to the python api and ontology-builder
- combine the coverage reports and submit to codecoverage.
- setup a GHA run to run codecoverge for prs and main
=> chore: enable code coverage

api/python/notebooks/Python API.ipynb, api/python/src/cellxgene_ontology_guide/ontology_parser.py, api/python/src/cellxgene_ontology_guide/supported_versions.py, api/python/tests/test_ontology_parser.py, api/python/tests/test_supported_versions.py
I think it makes more sense for it to live in supported_versions.py There is no need to initialize an OntologyParser object.
- update unit tests
- update notebook
- verify unit tests pass.
=> fix: move get_ontology_download_url.

api/python/src/cellxgene_ontology_guide/ontology_parser.py
- reformat the docstring with python code examples to high correctly in documentation.
=> chore: reformat examples in docstrings

.github/workflows/push-tests.yml
Fixing this error cause by updating to actions/upload-artifact@v4 and actions/download-artifact@v4
```
Run actions/upload-artifact@v4
With the provided path, there will be [1](https://github.com/chanzuckerberg/cellxgene-ontology-guide/actions/runs/8455804882/job/23164145371#step:7:1) file uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
=> chore: fix codecoverage

.github/workflows/release.yml
- Allow frontend consumers to get the latest release (without needing to make code changes to pin to a specific version), by providing a 'latest' tag that gets reassigned to the HEAD of main whenever a PyPI release occurs. 
- update release GHA to add a step to reassign the 'latest' tag immediately following a successful PyPI release
=> feat: tag most recently released commit as 'latest'

api/python/Makefile, api/python/pyproject.toml, tools/coverage.mk, tools/ontology-builder/Makefile, tools/ontology-builder/pyproject.toml
- moving pytest run configuration for unit tests into pyproject.toml. This is easier to maintain that in a makefile.
- moving pytest run configuration for unit tests into pyproject.toml
- update coverage/run to use testpaths from pyproject.toml
- verify coverage works and unit tests work for each test suite.
=> chore: move pytest configs to pyproject.toml

.github/workflows/generate_all_ontology.yml, README.md, api/python/src/cellxgene_ontology_guide/supported_versions.py, api/python/tests/test_ontology_parser.py, api/python/tests/test_supported_versions.py, artifact-schemas/ontology_info_schema.json, ontology-assets/ontology_info.json, tools/ontology-builder/src/all_ontology_generator.py, tools/ontology-builder/tests/test_all_ontology_generator.py
- automate the cellxgene schema versions deprecation process.
- https://github.com/chanzuckerberg/cellxgene-ontology-guide/issues/170
- add deprecation warning to API when older version of the cellxgene schema are used.
- add logic to all_ontology_generator.py to remove expired ontology files from repo, expired cellxgene schema versions from ontology_info.json, and deprecate the previous cellxgene schema version if a new version exists.
- updated unit tests
- Need to verify that files will be removed by the GHA.
=> chore: deprecate older version of cellxgene schema

api/python/src/cellxgene_ontology_guide/entities.py, api/python/src/cellxgene_ontology_guide/ontology_parser.py, api/python/tests/test_ontology_parser.py
- Cell Guide uses term label in their subtree implementation, this simplifies their integration with COG
- add "name" property to OntologyNode
- update dict representation of OntologyNode to accommodate this additional metadata on each node 
- Either list QA steps or reasoning you feel QA is unnecessary
- Describe how you made sure to know that your changes worked. Should allow someone else to go verify your code without in depth knowledge.
=> feat: add term label to OntologyNode

api/python/src/cellxgene_ontology_guide/ontology_parser.py, api/python/tests/test_ontology_parser.py
- Request from Cell Guide during integration for helper functions to fetch direct children / parents 
- add methods to ontology_parser to get direct children and get direct parents of ontology terms 
- refactor get_term_graph to leverage get_term_children
- update docstring to explicitly mention ValueError being raised in case of invalid and/or unsupported ontology term IDs passed in as input 
- unit tests + doctests
=> feat: add get_term_children and get_term_parents

api/python/src/cellxgene_ontology_guide/ontology_parser.py, api/python/tests/test_ontology_parser.py
- Account for census mapper's curated tissue general list being designed such that order of terms matters (see comment [here](https://github.com/chanzuckerberg/cellxgene-census/blob/861444a2100333459e7cdfed63519facc14a9f42/tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/tissue_mapper.py#L13-L14))
- return mapped high_level_terms matching an input term ID in the same order as the curated list passed in
- unit tests
=> fix: Preserve order of high_level_terms when matching against an input curated list of terms

.github/workflows/release.yml, api/python/pyproject.toml, api/python/src/cellxgene_ontology_guide/__init__.py, api/python/tests/test_version.py, release-please-config.json
- setuptools-scm and release-please don't play nice together. The [git command ](https://setuptools-scm.readthedocs.io/en/latest/config/#setuptools_scm.git.DEFAULT_DESCRIBE) command used by setuptools-scm is unable to parse the python-api version if multiple tags are on the same commit. This causes pypi releases to fail if they are released the same time as ontology-assets.
- remove setuptool-scm from the python-api build chain. 
- use release-please to update the python version values in the API
-  Ran release-please. This is what a release would look like https://github.com/chanzuckerberg/cellxgene-ontology-guide/pull/198
- verified unit tests pass
- reduces number of dependencies
- automated pypi releases will work reliably
- When build locally on a dirty branch, the version of COG …
=> fix: remove setuptools-scm

api/python/src/cellxgene_ontology_guide/ontology_parser.py, api/python/tests/test_ontology_parser.py
- #206
- add get_term_label_to_id_map to generate + return full term label to term ID maps by ontology_name, and cache them after they are generated once
- add get_term_id_by_label function to fetch single term IDs by their term label
- unit tests
=> feat: fetch term ID by term label

api/python/src/cellxgene_ontology_guide/ontology_parser.py, api/python/src/cellxgene_ontology_guide/supported_versions.py, api/python/tests/test_ontology_parser.py, api/python/tests/test_supported_versions.py, asset-schemas/ontology_info_schema.json, tools/ontology-builder/src/validate_json_schemas.py, tools/ontology-builder/tests/test_validate_json_schemas.py
- Continuation of https://github.com/chanzuckerberg/cellxgene-ontology-guide/issues/223 + experimental fruit fly and zebrafish dataset validation work
- define an instance attribute "imported_ontologies" in CXGScehma, a Dict[str, str] mapping all "additional_ontologies" defined in "ontology_info.json" to the source ontology it is imported in
- in OntologyParser, when querying for a given ontology prefix, determine if the prefix belongs directly to a supported ontology or if it belongs to an "additional_ontology" imported into a supported ontology. If it belongs to an imported ontology, use CXGScehma.imported_ontologies to find the source ontology it should query for that term (i.e. if a term ID is from an ontology that is an "addtitional_ontology" of ontology A, query ontology A metadata) …
=> feat: query cross-ontology terms imported into a supported ontology

api/python/notebooks/Python API.ipynb
changes this string from 5.0.0 to 5.3.0
=> feat: fix string error in python release

.github/workflows/release.yml
https://czi.atlassian.net/browse/CCIE-3911
This PR updates 'runs-on' in GitHub Actions workflow files to use direct values instead of label arrays.
=> fix: Update runs-on labels in GitHub Actions workflows
